### PR TITLE
Remove Batt Temp05 on Kona - is always set to 0

### PR DESCRIPTION
**Pull request by plord12**

### CODE REVIEW

**Comment by migle** [comment]
According to [this thread](https://www.ioniqforum.com/forum/234-hyundai-ioniq-electric-ev/28793-new-battery-layout-motor-components-hyundai-kia-electric-vehicles.html), there are 10 modules in the 64kWh Kona. The Ioniq has a temperature sensor for each of its 12 modules.
Additional bytes with module temperatures should be easy to spot, since they will be mostly with similar values.

**Comment by plord12** [comment]
Thanks for the link. but nothing jumped out at me looking at some dumps.

**Comment by ayokyun** [comment]
Thanks,
neither Niro EV doesn't have that sensor value.

I copied that from Soul EV, but it actually doesn't work for Kona/Niro EV.
It seems that Kona and Niro EV shard exact same PIDs.
What do you think of merging two folders?

**Comment by ayokyun** [comment]
> > What do you think of merging two folders?
> 
> Fine for me. Any minor differences can be in a separate file if needed.

Thanks,
Would you move PIDs which is verified by Kona EV and delete Kona EV folder?
Then I'll rename folder name from Niro EV to Niro&Kona EV.

**Comment by plord12** [comment]
I made an attempt at this .. 

Does anyone have a Niro EV (e-Niro) to do some verifying ?

**Pull request merged**
