### PR TITLE
Fix number of cells for Kona (was 96 now 98)

### PR DESCRIPTION
**Pull request by tibcoplord**

### CODE REVIEW

**Comment by JejuSoul** [comment]
Yes. The new 64kWh packs have 98 cell triplets. 
Thanks for adding the PID codes for the two extra cells.
Did you really see a voltage range from 4.3V to 2.5V ?

**Comment by plord12** [comment]
Yes the voltages looked right as did the average.

**Comment by piec2** [comment]
In the file, cells 97 and 98 have the same display name of '96' (small issue to be fixed)

**Comment by JejuSoul** [comment]
I have updated the files with cells 97 and 98.

**Comment by mairchik** [comment]
I see two versions for cell voltage ranges that are conflicting:
1) from 2.5V to 4.3V suggested and updated by tipcoplord
2) however JejuSoul did not updated the files and left ranges between 2.8V and 4.2V
Could you please clarify which version to use? 
For information if the same cells are used in Niro PHEV pack, the range should be between 2.5V and 4.2V as pointed here:
http://www.kniro.net/battery_pack_assembly_specifications-830.html
Thanks

**Pull request closed without merging**
