### PR TITLE
Update Hyundai_Ioniq_EV_VMCU_data.csv

### PR DESCRIPTION
**Pull request by kinnison**
I'm not saying this is the right thing to do, but there's a duplicated expression in the Ioniq EV VMCU file and you don't seem to have issues enabled so I couldn't file an issue.

D.

### CODE REVIEW

**Comment by ayokyun** [comment]
Thank you for your feedback!

**Comment by JejuSoul** [comment]
Thanks for noticing this.
The VMCU codes are bring created by ITStromer on the German Forum.
I don't have an Ioniq EV so hadn't checked the codes.
I will look at why issues is not setup. It should be.

**Comment by kinnison** [comment]
I'd love to be able to help ITStromer but I'm not yet well versed in how to decode these packets.  I am very happy to help you verify anything provided by them though.  I use a different tool for examining the CAN bus, but I can by-hand convert the torque CSV into something I can use :-)

**Comment by JejuSoul** [comment]
hmm. I am rereading the German forum - via Google translate.
https://www.goingelectric.de/forum/hyundai-ioniq-allgemeines/obd-diagnose-mit-torque-t21111-100.html
and see this - 

That this is obviously not the temperature values I noticed yesterday and today. The values sometimes also jump funny. Currently I log the values of the PIDs longer, maybe there are any patterns. Have therefore taken out of the last post, the PIDs, so that no one is unsettled

Can either of you confirm that this code is indeed a motor temp. Otherwise I think I will have to remove it entirely

**Comment by kinnison** [comment]
I can't confirm the motor temperature entry at all right now.  I only opened this PR because there wasn't a way to file an issue and I wanted to note that there were two entries pointing at the same bit of data.

I'll need to open my other laptop and see if I can find a CAN log from the OBC.  If I have it, it won't be from when the car was charging.  If you want, I can try and get some logs later this week from when it's charging.

**Comment by kinnison** [comment]
Now that you've enabled issues, perhaps we should move this to an issue, rather than a closed PR :-D

**Comment by kinnison** [comment]
It turns out that I don't have logs of the OBC itself (just of its response to 090A (request ECU name))  I'll see if I can get some logs for you later today or tomorrow.  What format is best for you?  Raw CAN, ISO-TP frame, or the UDS response packet?

**Comment by JejuSoul** [comment]
raw hex - 

Yes am moving this conversation to an issue.

**Comment by JejuSoul** [comment]
If you look in the Ray EV section you will see we have a spreadsheet that converts hex codes into the values they represent.
I will try to do the same with the Ioniq EV

**Pull request merged**
