### PR TITLE
First stab at Kona EV

### PR DESCRIPTION
**Pull request by plord12**
Heavily copied from Ioniq.  Only lightly tested on my Kona so far, I'm sure there is work to be done here.

Note that I've not actually tried a pull request before, so hopefully I've got this right !

### CODE REVIEW

**Comment by migle** [comment]
Congratulations! It works, doesn't it?

**Comment by migle** [comment]
Yes, it's the same with the Ioniq. You can also use the ELM-327 to listen on the bus (just not with Torque Pro), and yes, there is nothing. To get data, you must make a request. Be sure to check the other "Issues" thread, Issue #7 .

**Comment by asetyde** [comment]
Ok beautiful news ! Now I must put on mobile device to monitor recharging .. therefore I think Freematics , it's also packed

**Comment by asetyde** [comment]
https://freematics.com/pages/products/freematics-one-plus/

**Comment by asetyde** [comment]
I can use it ?

**Comment by asetyde** [comment]
Ok but preheat functions etc are not possible if not design, it's miracle if with car closed can I see status of battery ... this is my real goal ! But I must understand if can be used this adapter I think yes but I want a opinion of plord .. you not have idea if we can do this how many koners are enthusiast !

**Comment by migle** [comment]
> it's miracle if with car closed can I see status of battery ...

If it is similar to the Ioniq, then that is only possible if the car is charging. If the car is not ON and the car is not charging, then there is not communication via the OBD port.

**Comment by asetyde** [comment]
yes only when charging is goal

**Comment by plord12** [comment]
> > it's miracle if with car closed can I see status of battery ...
> 
> If it is similar to the Ioniq, then that is only possible if the car is charging. If the car is not ON and the car is not charging, then there is not communication via the OBD port.

Yes I tried this - with my Kona locked by charging, I can read the OBD info ( I tried with autopi BTW ).

**Comment by asetyde** [comment]
you can read status of charging  ? can send a shot of data collected

**Comment by plord12** [comment]
> you can read status of charging ? can send a shot of data collected

I only tried with autopi (https://www.autopi.io/) and using the command line, but I saw -

`
peter26@Kona $ obd.query test mode=220 pid=101 force=true
_type: test
_stamp: '2018-12-06T09:03:39.723470'
value: |-
  7EA037F2212
  7EB037F2212
  7EC103E620101FFF7E7
  7EC21FFBC18F4465003
  7EC22FF870FE60B0A0A
  7EC230A0A0A00000ACF
  7EC2453CF4A00009100
  7EC250015BF000012FD
  7EC2600000845000006
  7EC27D40006035E0901
  7EC28970000000003E8
  7ED037F2212
`

Viewing via the autopi cloud isn't yet ready :-(

**Comment by asetyde** [comment]
Ok but I think is better use Freematics, is more simple with arduinoESP32 core , I can use our lab to implement and do simple MQTT system to notify status of charge, therefore I must order .. when I ve time to develop it ! Where are you Plord ?

**Pull request merged**
