### PR TITLE
Outside temp sensor found

### PR DESCRIPTION
**Pull request by ITStromer**
Found the outside temp sensor at ECU 7E6. If it's okay we'll also merge it into VMCU_data.

### CODE REVIEW

**Comment by migle** [comment]
Thanks!

**Comment by Wekoyote** [comment]
Found SOC Display and SOH for the Ioniq PHEV. The rest of the CSV data is similar to the Ioniq EV, but these two are different.

[Hyundai_Ioniq_PHEV_BMS_data.csv.zip](https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs/files/3149888/Hyundai_Ioniq_PHEV_BMS_data.csv.zip)

**Comment by JejuSoul** [comment]
I added this change as Ambient Temp.

**Comment by JejuSoul** [comment]
I am going to close this pull request, because I have altered the file myself. 
The folder name for the Ioniq has been changed to show the 28kWh battery size.

**Pull request closed without merging**
